# Configuration for Regulatory Document RAG System

# Document paths
document_paths:
  policies: "./policies"
  standards: "./standards"

# Output paths
faiss_store:
  index_path: "./faiss_store/faiss_index.faiss"
  metadata_path: "./faiss_store/metadata.json"

# Embedding configuration
embedding:
  provider: "sentence-transformers"  # Options: sentence-transformers, openai, cohere
  model_name: "all-mpnet-base-v2"   # Model name for the chosen provider
  # api_key: "your_api_key_here"     # Required for openai/cohere

# Alternative embedding options:
# For OpenAI:
# embedding:
#   provider: "openai"
#   model_name: "text-embedding-3-small"
#   api_key: "your_openai_api_key"

# For Cohere:
# embedding:
#   provider: "cohere" 
#   model_name: "embed-english-v3.0"
#   api_key: "your_cohere_api_key"

# Chunking configuration
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  preserve_structure: true
  min_chunk_size: 100

# FAISS configuration
faiss:
  index_type: "IndexFlatIP"  # Options: IndexFlatIP, IndexFlatL2, IndexIVFFlat
  normalize_vectors: true

# Search configuration
search:
  default_k: 5
  score_threshold: 0.7
  max_results: 20